-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA
WHERE ID IN 
( SELECT A.ID
  FROM   ECOLI_DATA AS A, 
    (
        SELECT B.ID, B.PARENT_ID
        FROM ECOLI_DATA AS A, ECOLI_DATA AS B
        WHERE A.ID = B.PARENT_ID AND A.PARENT_ID IS NULL
    ) AS B
  WHERE A.PARENT_ID = B.ID 
)
ORDER BY ID