-- 코드를 작성해주세요
WITH RECURSIVE generations AS (
    # 초기 조건
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION 
    
    # 재귀 : 덧붙이기
    SELECT N.ID, N.PARENT_ID, G.GENERATION +1
    FROM ECOLI_DATA N
    JOIN generations G on G.ID = N.PARENT_ID
    
)
SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM generations as G
WHERE ID NOT IN
(SELECT PARENT_ID
 FROM ECOLI_DATA
 WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION