-- 코드를 작성해주세요

SELECT YEAR_SIZE.YEAR, (YEAR_SIZE.MAX_SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN ( SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE) 
) AS YEAR_SIZE ON YEAR_SIZE.YEAR = YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR_SIZE.YEAR, YEAR_DEV

