-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B 
ON A.FISH_TYPE = B.FISH_TYPE,
(
SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE
) AS M

  
WHERE A.FISH_TYPE = M.FISH_TYPE AND A.LENGTH = M.LENGTH
ORDER BY A.ID


