-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, EP.EMP_NO, EP.EMP_NAME, EP.POSITION, EP.EMAIL
FROM HR_EMPLOYEES AS EP

JOIN HR_GRADE AS GR ON EP.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = 2022
GROUP BY EP.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
